language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r hailey-springboot-webservice-project
  - mkdir -p deploy
  - mv hailey-springboot-webservice-project.zip deploy/hailey-springboot-webservice-project.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: hailey-springboot-webservice-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

# CI 실행 완료 시 메일로 알림
notifications:
  email:
    recipients:
      - hyerijung0903@gmail.com
