branches: 
  only: 
    - master
cache: 
  directories: 
    - $HOME/.m2/repository
    - $HOME/.gradle
jdk: 
  - openjdk8
language: java
notifications: 
  email: 
    recipients: 
      - hyerijung0903@gmail.com
script: "./gradlew clean build"
