language: java

jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r hailey-springboot-webservice *. # zip에 포함시킬 파일들을 담을 디렉토리 생성
  - mkdir -p deploy
  - mv hailey-springboot-webservice.zip deploy/hailey-springboot-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: hailey-springboot-build #S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true
    
 - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: hailey-springboot-build # S3 버킷
    key: hailey-springboot-webservice.zip # 빌드 파일을 압축해서 전달
    bundle_type: zip
    application: hailey-springboot-webservice # 웹 콘솔에서 등록한 CodeDeploy 어플리케이션
    deployment_group: hailey-springboot-webservice-group # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
    region: ap-northeast-2
    wait-until-deployed: false

# CI 실행 완료 시 메일로 알림
notifications:
  email:
    recipients:
      - hyerijung0903@gmail.com
